name: Daily ECMWF Download

permissions:
  contents: write

on:
  schedule:
    - cron: "16 00 * * *"  # every day at 02:00 UTC
  workflow_dispatch:      # allows manual run

jobs:
  download:
    runs-on: ubuntu-latest
    env:
      ECMWF_API_URL: ${{ secrets.ECMWF_API_URL }}
      ECMWF_API_KEY: ${{ secrets.ECMWF_API_KEY }}
      ECMWF_API_EMAIL: ${{ secrets.ECMWF_API_EMAIL }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # - name: Run download script
      #   if: ${{ env.ECMWF_API_URL != '' }}
      #   run: |
      #     python download_s2s.py

      # - name: Upload GRIB file as artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: s2s_grib
      #     path: data/*.grib

      # - name: Generate plots
      #   run: |
      #     python plot_s2s.py

      # - name: Upload plots as artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: s2s_plots
      #     path: plots/**/*.png

      # - name: Upload netCDF file as artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: s2s_nc
      #     path: data/*.nc

      # - name: perform downscaling
      #   run: |
      #     python dowscale_dekade.py

      # - name: Upload plots as artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: downscale_plots
      #     path: plots/**/*.png

      # - name: Upload netCDF file as artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: s2s_nc
      #     path: data/*.nc

      - name: Save generated files in repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add plots/
          git add data/
          git commit -m "Daily automated update" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Get EMCWF lagged date
        id: ecmwf_date
        run: echo "::set-output name=date::$(date -d '3 days ago' +'%Y-%m-%d')"

      - name: download tahmo data 
        run: |
          python get_tahmo_data.py --country Kenya

      - name: download imerg data 
        run: |
          python get_imerg_data.py --country Kenya

      - name: generate plots
        run: |
          python plot_sat_vs_stations.py --country Kenya

      - name: Email out generated plots
        uses: dawidd6/action-send-mail@v16
        with:
          server_address: smtp.resend.com
          server_port: 587
          username: resend
          password: ${{ secrets.RESEND_API_KEY }}
          subject: Daily S2S Outlook
          to: genevieve@rhizaresearch.org, josh@rhizaresearch.org
          from: 'Nimbus Data Share <info@dashboards.rhizaresearch.org>'
          body: Attached are the dekadal outlooks and historical station data related to the subseasonal forecast. You can also view the data (except for the station data) at ${{ github.server_url }}/${{ github.repository }}.
          reply_to: genevieve@rhizaresearch.org
          attachments: >
            plots/Kenya/${{ steps.ecmwf_date.outputs.date }}/dekadal/dekadal_precip.png, 
            plots/Kenya/${{ steps.ecmwf_date.outputs.date }}/weekly/weekly_precip.png, 
            plots/Kenya/${{ steps.ecmwf_date.outputs.date }}/dekadal/imerg_Kenya_dekadal.png, 
            plots/Kenya/${{ steps.ecmwf_date.outputs.date }}/weekly/imerg_Kenya_weekly.png, 
            private_plots/Kenya/${{ steps.date.outputs.date }}/*.png, 
            private_data/Kenya/${{ steps.date.outputs.date }}/*.csv